### ISSUE TITLE
Display Progress Bar on Remote Website

### ISSUE THREAD

**Issue by du8die** [pieceofsummer/Hangfire.Console#19]
Good Evening,

Is there any way (using an API, or something) to display the progress bar of a job on a remote site? I'd like to provide end users with a view of the progress of their jobs - without giving them access to the Hangfire dashboard.

Thanks

**Comment by pieceofsummer** [comment]
Each console is bound to a Processing state of a job, and a job may have multiple Processing states (for example, because of automatic or manual retries). There's currently no simple way to get the last Processing state of a job, so it would require some trickery.

Also the data endpoint for AJAX requests is located under /dashboard path, and is a subject for Hangfire's authorization policies. It won't be accessible for users who are not authorized to access dashboard.

But you can build your own public API endpoint to overcome all these issues.

**Comment by pieceofsummer** [comment]
It was also requested in #21, so I've added API to access console data.

Now you may use it in your MVC controller to expose data to users. Something like:

```c#
public IActionResult GetProgress(string jobId)
{
    if (string.IsNullOrEmpty(jobId))
        throw new ArgumentNullException(nameof(jobId));

    var job = JobStorage.Current.GetMonitoringApi().JobDetails(jobId);
    if (job == null)
        return NotFound();

    double? progress = null;

    var state = job.History.FirstOrDefault(s => s.StateName == ProcessingState.StateName);
    if (state != null)
    {
        using (var consoleApi = JobStorage.Current.GetConsoleApi())
        {
            var lines = consoleApi.GetLines(jobId, 
                    JobHelper.DeserializeDateTime(state.Data["StartedAt"]), 
                    LineType.ProgressBar);
            if (lines.Count > 0)
                progress = lines[0].Progress;
        }
    }

    return Json(new { 
        State = job.History[0].State, 
        Reason = job.History[0].Reason, 
        Progress = progress 
    });
}
```
