### ISSUE TITLE
Getting console messages via MonitoringApi

### ISSUE THREAD

**Issue by dyha89** [pieceofsummer/Hangfire.Console#21]
Hi

Is there a possibility to get messages logged by Hangfire.Console using JobStorage.Current.GetMonitoringApi().JobDetails(jobId) method?

**Comment by pieceofsummer** [comment]
Not at the moment. But could be done by providing a few extension methods for IMonitoringApi.

**Comment by dyha89** [comment]
Thanks for answer!

So there is no "out of box" way to get ConsoleLine objects by jobId?

Only idea I have for the moment is to get ConsoleStorage instance by reflection and try to get some using this class.

**Comment by pieceofsummer** [comment]
Please take a look at v1.2.1, which adds an initial version of `IConsoleApi` interface (similar to `IMonitoringApi`) to access console data. It only contains a single method `GetLines()` for now, but may be extended in the future.

Here's an example:
```c#
using (var consoleApi = JobStorage.Current.GetConsoleApi())
{
    var job = JobStorage.Current.GetMonitoringApi().JobDetails(jobId);

    foreach (var state in job.History.Where(s => s.StateName == ProcessingState.StateName))
    {
        var lines = consoleApi.GetLines(jobId, JobHelper.DeserializeDateTime(state.Data["StartedAt"]));
        // do something with lines
    }
}
```

There's also an optional argument to get only lines of a certain type (`LineType.Text` or `LineType.ProgressBar`).

**Comment by dyha89** [comment]
Great! Thanks a lot for new version ;)
I'll try it in a few next days, and post some feedback.

**Comment by dyha89** [comment]
Solution works perfectly ;)
Thanks for your help ;)

**Comment by artjomzab** [comment]
@pieceofsummer what is the purpose of JobHelper.DeserializeDateTime(state.Data["StartedAt"])? Why do you need this timestamp to get the lines?

**Comment by blueboxes** [comment]
The data is stored with a key based on the start time so that is why is needed to look it up. As a side note it is an Epoc so is millisecond accurate. 

The XML comments say it is the time processing was started and then point to create date property. 

https://github.com/pieceofsummer/Hangfire.Console/blob/a1fea1356c46fe70b0a9df1785cf5c138aa18ae0/src/Hangfire.Console/Monitoring/IConsoleApi.cs#L16

However, these are not the same; the started processing date is needed. This is only available in the data dictionary on the processing task and is a string.

Finally to make use of the lines you will need to cast them to either `TextLineDto` or `ProgressBarDto`  otherwise you only have access to the colour and timestamp.
