### ISSUE TITLE
PerformContext.WriteLine is not thread safe

### ISSUE THREAD

**Issue by andrewgluh** [pieceofsummer/Hangfire.Console#43]
Running the below code (using SQL server) throws a TransactionInDoubtException error:

> var tenants = new List`<int>`{ 1, 2, 3, 4, 5, 6 };
> Parallel.ForEach(tenants, new ParallelOptions { MaxDegreeOfParallelism = 3 }, tenant =>
> {
>     context.WriteLine("test message");
> }

**Comment by pieceofsummer** [comment]
Worked fine on my machine :)

What is an `InnerException` of the `TransactionInDoubtException` you get?

I've found another thread-safety issue though when there are fewer lines than expected (because time correction for duplicate lines is performed in an unsafe manner).

I've pushed v1.3.8 update, it might fix your issue as well.

**Comment by andrewgluh** [comment]
Yes, that works now.
Thanks!
