### ISSUE TITLE
Ability to render html

### ISSUE THREAD

**Issue by lanierhall** [pieceofsummer/Hangfire.Console#48]
Is there a way to hit a GET route and then render the HTML content.

Basically I have html as a string and would like to render it instead of printing out the raw html.

**Comment by pieceofsummer** [comment]
I don't want to implement the arbitrary HTML support because it could easily break the layout and stop the client-side JS from functioning correctly.

I may consider limited HTML support though, supporting just a few "safe" tags and styles. But it's probably not what you want. There wouldn't be any scripts, images or other interactive content there.

**Comment by lanierhall** [comment]
Ok, thanks for responding.
